name: Deploy to Production
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Front Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        tags: yucacodes/anchat-front:${{ github.sha }}
        push: true
        target: front
    - name: Build and push Server Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        tags: yucacodes/anchat-server:${{ github.sha }}
        push: true
        target: server
        
